import static java.util.Arrays.sort;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Task2 {
    public int solution(int[] A) {
        // The only way to don' have any adjacent distance is if we just
        // have one element...
        if (A.length == 1) return -2;

        // Sorting is the trick, we have all adjacent values in
        // adjacent indexes
        sort(A);

        // We need to use long, because the distance could be between
        // Integer.MIN_VALUE and Integer.MAX_VALUE
        long min = Long.MAX_VALUE;

        // Find the min distance between adjacent indexes
        for (int i = 1; i < A.length; i++) {
            long distance = Math.abs(A[i] - A[i-1]);
            min = Math.min(distance, min);
        }

        if (min > 100000000) return -1;

        return (int)min;
    }
}
