/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class Task2Test {
    @Test public void testSomeLibraryMethod() {
        Task2 classUnderTest = new Task2();
        int[] a = new int[] { 1, 5, 3 , 3, 7};

        assertThat(classUnderTest.solution(a), is(0));
    }
}
