/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class Task3Test {
    @Test public void testSomeLibraryMethod() {
        Task3 classUnderTest = new Task3();
        int[] a = new int[] { 3, 4, 7, 7, 6, 6};
        assertThat(classUnderTest.solution(a), is(3));

        int[] b = new int[] { 80, 80, 1000000000, 80, 80, 80, 80, 80, 80, 123456789};
        assertThat(classUnderTest.solution(b), is(3));
    }
}
