/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class Task1Test {
    @Test public void testSomeLibraryMethod() {
        Task1 classUnderTest = new Task1();
        int[] a = new int[] { 1, 5, 3 , 3, 7};
        assertThat(classUnderTest.yourFunction(a), is(true));
    }
}
